[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
# optimizer = true
# optimizer_runs = 100000
# evm_version = "london"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
